version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

volumes:
  mongo_data:
